//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagsCloudCore.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagsCloudCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] en_us_aff {
            get {
                object obj = ResourceManager.GetObject("en_us_aff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 48974
        ///0/nm
        ///0th/pt
        ///1/n1
        ///1st/p
        ///1th/tc
        ///2/nm
        ///2nd/p
        ///2th/tc
        ///3/nm
        ///3rd/p
        ///3th/tc
        ///4/nm
        ///4th/pt
        ///5/nm
        ///5th/pt
        ///6/nm
        ///6th/pt
        ///7/nm
        ///7th/pt
        ///8/nm
        ///8th/pt
        ///9/nm
        ///9th/pt
        ///A/SM
        ///AA/M
        ///AAA
        ///AB/M
        ///ABA
        ///ABC/SM
        ///ABM/SM
        ///ABS
        ///AC/M
        ///ACLU/M
        ///ACT
        ///ACTH/M
        ///AD/M
        ///ADC
        ///ADD
        ///ADM
        ///ADP/M
        ///AF
        ///AFAIK
        ///AFB
        ///AFC/M
        ///AFDC
        ///AFN
        ///AFT
        ///AI/SM
        ///AIDS/M
        ///AK
        ///AL
        ///AM/M
        ///AMA
        ///AMD/M
        ///ANSI/S
        ///ANZUS/M
        ///AOL/M
        ///AP/M
        ///APB
        ///APC
        ///API
        ///APO
        ///APR
        ///AR
        ///ARC
        ///ASAP
        ///ASCII/SM
        ///ASL/M
        ///ASPCA
        ///ATM/M
        ///ATP/M
        ///ATV
        ///AV
        ///AVI
        ///AWACS/M
        ///AWOL/M
        ///AZ/M
        ///AZT/M
        ///Aachen/M
        ///Aaliyah/M
        ///Aaron/M
        ///Abbas/M
        ///Abbasid/M
        ///Abbott/M
        ///Abby/M
        ///Abdul/M
        ///Abe/M
        ///Abel/M
        ///Abela [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string en_us_dic {
            get {
                return ResourceManager.GetString("en_us_dic", resourceCulture);
            }
        }
    }
}
