input: examples/sample1.txt
# output: output.png
max-font-size: 40
layouter: random
background-color: "#660000"
foreground-color: "#259925"
font-family: "Cambria Math"
max-tags-count: 300
width: 900
height: 900